/*******************************************************************************
 * Copyright (c) 2024 Ericsson.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
pipeline {
    agent {
        kubernetes {
            label 'tracecompass-test-traces-build'
            yamlFile 'jenkins/pod-templates/tracecompass-test-traces-pod.yaml'
        }
    }
    options {
        timestamps()
        timeout(time: 1, unit: 'HOURS')
        disableConcurrentBuilds()
    }
    tools {
        maven 'apache-maven-3.9.5'
        jdk 'openjdk-jdk17-latest'
    }
    environment {
        MAVEN_OPTS="-Xms768m -Xmx4096m -XX:+UseSerialGC"
    }
    stages {
        stage('Build') {
            steps {
                container('tracecompass') {
                    sh 'mvn clean install -Dmaven.repo.local=$WORKSPACE/.m2/repository ${MAVEN_ARGS}'
                }
            }
            post {
                always {
                    container('tracecompass') {
                        junit '**/target/surefire-reports/*.xml'
                    }
                }
            }
        }
    }
}
